name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: Name of uploaded artifact
        required: false
      upload-artifacts:
        type: boolean
        description: Whether to upload artifacts
        required: false
        default: false
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy files for upload
        run: |
          mkdir -p dist
          cd dist
          echo "a" > a.txt
          echo "b" > b.txt

      - name: Upload artifacts
        if: fromJSON(inputs.upload-artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
          retention-days: 1
          if-no-files-found: error
