name: Build
on:
  push:
    branches:
      # Main stable branch
      - 'master'
      # Release preparation/support branches
      - 'release/**'
    paths-ignore:
      - '*.md'
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Dummy task
        run: echo Hello

  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Dummy task
        run: echo Hello
