name: Build
on:
  workflow_call:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy files for upload
        run: |
          mkdir -p dist
          cd dist
          echo "a" > a.txt
          echo "b" > b.txt
