name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  build:
    uses: ./.github/workflows/build.yaml

  build-pr:
    needs:
      - build
    uses: ./.github/workflows/build-pr.yaml
