name: CI
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      release-tag: ${{ steps.vars.outputs.release-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: vars
        run: |
          echo "release-tag=$(cat version.txt)" >> "${GITHUB_OUTPUT}"

  build:
    needs:
      - vars
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy files for upload
        run: |
          mkdir -p dist
          cd dist
          echo "a" > a.txt
          echo "b" > b.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1
          if-no-files-found: error

  build-pr:
    if: github.event_name == 'pull_request'
    needs:
      - build
      - vars
    runs-on: ubuntu-22.04
    steps:
      - name: Dummy task
        run: echo Hello

  create-release:
    # Release preparation/support branche merged
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.head_ref, 'release/')
    needs:
      - build
      - build-pr
      - vars
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - name: Import PGP private key
        env:
          PGP_KEY_ID: ${{ vars.PGP_KEY_ID }}
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
        run: |
          gpg --batch --import <<EOF
          ${PGP_PRIVATE_KEY}
          EOF
          gpg --batch --command-fd 0 --edit-key "${PGP_KEY_ID}" trust <<EOF
          5
          y
          EOF

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create checksum file
        env:
          PGP_KEY_ID: ${{ vars.PGP_KEY_ID }}
          PGP_KEY_PASSPHRASE: ${{ secrets.PGP_KEY_PASSPHRASE }}
        run: |
          sha256sum * > SHA256SUMS
          gpg --batch --pinentry-mode loopback --local-user "${PGP_KEY_ID}" --detach-sign --armor --passphrase-fd 0 SHA256SUMS <<EOF
          ${PGP_KEY_PASSPHRASE}
          EOF
        working-directory: dist

      - name: List artifacts
        run: find dist/ || exit 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-checksums
          path: |
            dist/*.asc
            dist/*SUMS
          retention-days: 1
          if-no-files-found: error

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.vars.outputs.release-tag }}
        run: gh release create --draft "${RELEASE_TAG}" dist/* || exit 1
