name: CI
on:
  push:
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build:
    uses: ./.github/workflows/build.yaml

  build-pr:
    if: github.event_name == 'pull_request'
    needs:
      - build
    uses: ./.github/workflows/build-pr.yaml
