name: CI
on:
  push:
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build-baseline:
    uses: ./.github/workflows/build-baseline.yaml

  prepare-artifacts:
    needs:
      - build-baseline
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/prepare-artifacts

  build-additional:
    if: github.event_name == 'pull_request'
    needs:
      - build-baseline
    uses: ./.github/workflows/build-additional.yaml
