name: Release
on:
  pull_request_target:
    branches:
      # Release preparation/support branches
      - 'release/**'
    types:
      - closed
defaults:
  run:
    shell: bash
jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
    steps:
      - id: vars
        run: |
          echo "release-tag=$(cat version.txt)" >> "${GITHUB_OUTPUT}"

  publish-on-merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy files for upload
        run: |
          echo "a" > a.txt
          echo "b" > b.txt
        working-directory: dist

      - name: Create checksum file
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
        run: |
          sha256sum * > SHA256SUMS
        working-directory: dist

      - name: List artifacts
        run: find dist/ || exit 1

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --draft "${{ needs.vars.outputs.release-tag }}" dist/* || exit 1
