name: Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      release-tag: ${{ steps.vars.outputs.release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: vars
        run: |
          echo "release-version=$(cat version.txt)" >> "${GITHUB_OUTPUT}"

  build:
    uses: ./.github/workflows/build.yaml

  create-github-release-draft:
    needs:
      - build
      - vars
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: vars
        run: |
          echo "release-tag=$(cat version.txt)" >> "${GITHUB_OUTPUT}"

      - name: Set up signing
        uses: ./.github/workflows/setup-sign
        with:
          pgp-key-id: ${{ vars.PGP_KEY_ID }}
          pgp-key-passphrase: ${{ secrets.PGP_KEY_PASSPHRASE }}
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          git-user-email: ${{ vars.GIT_USER_EMAIL }}
          git-user-name: ${{ vars.GIT_USER_NAME }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Sign artifacts
        run: gpg --batch --pinentry-mode loopback --detach-sign --armor SHA256SUMS
        working-directory: dist

      - name: List artifacts
        run: find dist/

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.vars.outputs.release-tag }}
        run: gh release create --draft "${RELEASE_TAG}" dist/*

  tag-release:
    needs:
      - create-github-release-draft
      - vars
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up signing
        uses: ./.github/workflows/setup-sign
        with:
          pgp-key-id: ${{ vars.PGP_KEY_ID }}
          pgp-key-passphrase: ${{ secrets.PGP_KEY_PASSPHRASE }}
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          git-user-email: ${{ vars.GIT_USER_EMAIL }}
          git-user-name: ${{ vars.GIT_USER_NAME }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: List artifacts
        run: find dist/

      - name: Tag release
        env:
          RELEASE_VERSION: ${{ needs.vars.outputs.release-version }}
          RELEASE_TAG: ${{ needs.vars.outputs.release-tag }}
        run: |
          git tag --sign --message "Release ${RELEASE_VERSION}" "${RELEASE_TAG}"
          git push origin "${RELEASE_TAG}"

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.vars.outputs.release-tag }}
        run: gh release edit --verify-tag "${RELEASE_TAG}"

  delete-github-deployments:
    if: always()
    needs:
      - tag-release
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    steps:
      - name: Delete inactive deployments
        uses: actions/github-script@v7
        env:
          GITHUB_SHA_HEAD: ${{ github.event.pull_request.head.sha }}
        with:
          # https://github.com/actions/runner/issues/2120#issuecomment-1336193335
          script: |
            const { sha } = context;
            const { owner, repo } = context.repo;
            const deployments = await github.rest.repos.listDeployments({ owner, repo, sha });
            await Promise.all(
              deployments.data.map(async (deployment) => {
                await github.rest.repos.createDeploymentStatus({
                  owner,
                  repo,
                  deployment_id: deployment.id,
                  state: "inactive"
                });
                return github.rest.repos.deleteDeployment({
                  owner,
                  repo,
                  deployment_id: deployment.id
                });
              })
            );
